replicaCount: 2

image:
  repository: alokdocker8700/novapay
  tag: bf77693aca4e9cb3eb3f07991647643f881526b4
  pullPolicy: Always

container:
  port: 4000

service:
  type: ClusterIP
  port: 4000
  targetPort: 4000

gateway:
  ingressClassName: alb
  scheme: internet-facing
  targetType: ip

  certificateArn: arn:aws:acm:us-east-1:274193347237:certificate/e23ad132-4bb6-4292-83dc-7ce080ca4b94

  host: devops-skill.xyz
  wwwHost: www.devops-skill.xyz

config:
  NODE_ENV: production
  PORT: "4000"

secret:
  existingSecret: novapay-secret

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

monitoring:
  serviceMonitor:
    enabled: true
    interval: 15s
    path: /metrics
    labels:
      release: monitoring

  prometheusRule:
    enabled: true
    labels:
      release: monitoring
